// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDarwfwC-n2_GaLFS0rxxl19Ae1SlY55KA',
    appId: '1:722359653246:web:16bf2c47d6995cee61192f',
    messagingSenderId: '722359653246',
    projectId: 'darkcinema-bd731',
    authDomain: 'darkcinema-bd731.firebaseapp.com',
    storageBucket: 'darkcinema-bd731.firebasestorage.app',
    measurementId: 'G-K2T0XE1C66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7a1iIUYic3vKdIAcswyQuSuiyTqFbc6Q',
    appId: '1:722359653246:android:c1dcfa67fc9cc0dc61192f',
    messagingSenderId: '722359653246',
    projectId: 'darkcinema-bd731',
    storageBucket: 'darkcinema-bd731.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhaKTGog4Nl35zd1Ddc2zp8q8uR3T8Noc',
    appId: '1:722359653246:ios:0ec500ad193532f261192f',
    messagingSenderId: '722359653246',
    projectId: 'darkcinema-bd731',
    storageBucket: 'darkcinema-bd731.firebasestorage.app',
    iosBundleId: 'com.example.darkCinemax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhaKTGog4Nl35zd1Ddc2zp8q8uR3T8Noc',
    appId: '1:722359653246:ios:0ec500ad193532f261192f',
    messagingSenderId: '722359653246',
    projectId: 'darkcinema-bd731',
    storageBucket: 'darkcinema-bd731.firebasestorage.app',
    iosBundleId: 'com.example.darkCinemax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDarwfwC-n2_GaLFS0rxxl19Ae1SlY55KA',
    appId: '1:722359653246:web:5236f74005d7978961192f',
    messagingSenderId: '722359653246',
    projectId: 'darkcinema-bd731',
    authDomain: 'darkcinema-bd731.firebaseapp.com',
    storageBucket: 'darkcinema-bd731.firebasestorage.app',
    measurementId: 'G-NPF5HKVEC3',
  );
}
